name: adriel_flutter_app
description: Adriel flutter portfolio app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  english_words: ^4.0.0
  provider: ^6.0.0
  devtools_shared: ^6.0.0
  dev: ^1.0.0
  flutter_slider_indicator: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

dependency_overrides:
  path_provider: 2.0.1