name: adriel_flutter_app
description: Adriel flutter portfolio app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  english_words: ^4.0.0
  provider: ^6.1.1
  devtools_shared: ^6.0.0
  dev: ^1.0.0
  card_actions: ^0.0.1
  swiping_card_deck: ^1.3.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  swipe_to: ^1.0.4
  dartz: ^0.10.1
  flutter_contacts: ^1.1.7+1
  # Flutter Quill Packages
  flutter_quill: ^8.5.5
  flutter_quill_extensions: ^0.6.10
  quill_html_converter: ^0.0.1-experimental.1

  # Plugins
  image_cropper: ^5.0.0
  path_provider: ^2.1.1
  # For drag and drop feature
  desktop_drop: ^0.4.4
  # For picking quill document files
  file_picker: ^6.1.1
  # For sharing text
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/shooter-game.png
    - assets/images/krishna.png
    - assets/images/air-battle-game.png
    - assets/images/react-app.png
    - assets/images/exchange.png
    - assets/images/krishna.png
    - assets/images/frontend-challenges.png
    - assets/images/dice-game.png
    - assets/images/react-app.png
    - assets/images/shooter-game.png
    - assets/images/air-battle-game.png
    - assets/images/haribol-store.png
    - assets/images/tic-tac-toe.png
    - assets/images/simple-rocket.png
    - assets/images/haribol-store.png
    - assets/images/exchange.png
    - assets/images/tic-tac-toe.png
    - assets/images/frontend-challenges.png
    - assets/images/chat-clone.png
    - assets/images/chat-clone.png
    - assets/images/3d-port.png
    - assets/images/3d-port.png
    - assets/images/vue-port.png
    - assets/images/vue-port.png


dependency_overrides:
  path_provider: 2.0.1

  